<?xml version="1.0"?>
<package format="2">
  <name>wam_sim_node</name>
  <version>0.0.0</version>
  <description>The test package</description>
  <maintainer email="support@barrett.com">Barrett Technology Inc.</maintainer>
  <license>GPL</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>moveit_core</build_depend>
  <exec_depend>moveit_core</exec_depend>
  <build_depend>roscpp</build_depend>
  <exec_depend>roscpp</exec_depend>
  <build_depend>sensor_msgs</build_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <build_depend>std_msgs</build_depend>
  <exec_depend>std_msgs</exec_depend>
  <build_depend>std_srvs</build_depend>
  <exec_depend>std_srvs</exec_depend>
  <build_depend>tf</build_depend>
  <exec_depend>tf</exec_depend>
  <build_depend>tf_conversions</build_depend>
  <exec_depend>tf_conversions</exec_depend>
  <build_depend>eigen_conversions</build_depend>
  <exec_depend>eigen_conversions</exec_depend>
  <build_depend>geometry_msgs</build_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <build_depend>moveit_commander</build_depend>
  <exec_depend>moveit_commander</exec_depend>
  <build_depend>moveit_fake_controller_manager</build_depend>
  <exec_depend>moveit_fake_controller_manager</exec_depend>
  <build_depend>moveit_msgs</build_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <build_depend>moveit_planners_ompl</build_depend>
  <exec_depend>moveit_planners_ompl</exec_depend>
  <build_depend>moveit_ros_control_interface</build_depend>
  <exec_depend>moveit_ros_control_interface</exec_depend>
  <build_depend>moveit_ros_manipulation</build_depend>
  <exec_depend>moveit_ros_manipulation</exec_depend>
  <build_depend>moveit_ros_move_group</build_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <build_depend>moveit_ros_perception</build_depend>
  <exec_depend>moveit_ros_perception</exec_depend>
  <build_depend>moveit_ros_planning</build_depend>
  <exec_depend>moveit_ros_planning</exec_depend>
  <build_depend>moveit_ros_planning_interface</build_depend>
  <exec_depend>moveit_ros_planning_interface</exec_depend>
  <build_depend>moveit_ros_robot_interaction</build_depend>
  <exec_depend>moveit_ros_robot_interaction</exec_depend>
  <build_depend>moveit_ros_visualization</build_depend>
  <exec_depend>moveit_ros_visualization</exec_depend>
  <build_depend>moveit_ros_warehouse</build_depend>
  <exec_depend>moveit_ros_warehouse</exec_depend>
  <build_depend>moveit_setup_assistant</build_depend>
  <exec_depend>moveit_setup_assistant</exec_depend>
  <build_depend>moveit_simple_controller_manager</build_depend>
   <exec_depend>moveit_simple_controller_manager</exec_depend>
  <build_depend>rqt_moveit</build_depend>
   <exec_depend>rqt_moveit</exec_depend>
  <export>
  </export>
</package>
